sites/urls.py
from django.urls import path

from .views import (
    SiteDetailView,
    SiteCreateView,
    SiteUpdateView,
    SiteDeleteView,
    export_sites_csv,
    import_sites_csv,
    sites_grid
)

app_name = "sites"
urlpatterns = [
    path('', sites_grid, name='site-grid'),
    path('<int:id>/', SiteDetailView.as_view(), name='site-detail'),
    path('create/', SiteCreateView.as_view(), name='site-creation'),
    path('<int:id>/update/', SiteUpdateView.as_view(), name='site-update'),
    path('<int:id>/delete/', SiteDeleteView.as_view(), name='site-delete'),
    path('export', export_sites_csv, name='site-export-csv'),
    path('import', import_sites_csv, name='site-import-csv'),
]

www/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pminstrumentation.urls')),
    path('about', include('pminstrumentation.urls')),
    path('contact', include('pminstrumentation.urls')),
    path('legals', include('pminstrumentation.urls')),
    path('customers/', include('customers.urls')),
    path('sites/', include('sites.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('planning/', include('planning.urls')),
    path('notifications/', include('notifications.urls')),
    path('tickets/', include('tickets.urls')),
]

sites/models.py
from django.db import models
from django.urls import reverse
from django.http import HttpResponseRedirect

from customers.models import Customer

class Site(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    country = models.CharField(max_length=500)
    state = models.CharField(max_length=500)
    city = models.CharField(max_length=500)
    postal = models.CharField(max_length=500)
    address = models.CharField(max_length=500)

    def get_absolute_url(self):
        return reverse("sites:site-detail", kwargs={"id":self.id})

sites/forms.py
from django import forms

from .models import Site

class SiteModelForm(forms.ModelForm):
    class Meta:
            model = Site
            fields = [
                "customer",
                "name",
                "country",
                "state",
                "city",
                "postal",
                "address"
            ]

sites/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required
from customers.models import Customer
from .models import Site
from .forms import SiteModelForm

import csv, os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

@permission_required("sites_write","sites_all")
def import_sites_csv(request):
    if request.method == 'POST' and request.FILES:                              #avoid GET and empty file sending
        file = request.FILES['file'].read().decode("utf-8")           #get the file and open it to read with UTF-8 compatibility
        rows = file.split("\n")                                                 #get rows (separator : \n)
        for row in rows:                                                        #loop through rows
            if row != '':                                                       #avoid last empty row
                col = row.split(",")                                            #get columns (delimiter : ,)
                if col[0] != 'customer':                                            #skip header
                    _, cus = Customer.objects.get_or_create(
                        id=col[0],
                        defaults={"name":"Default customer","label":"Default customer label","siren":"999999999"}
                    )

                    if isinstance(cus, Customer):
                        customer = cus
                    else:
                        customer = _

                    _, created = Site.objects.get_or_create(                #check existence in database to avoid duplicate
                        customer    = customer,
                        name        = col[1],
                        country     = col[2],
                        state       = col[3],
                        city        = col[4],
                        postal      = col[5],
                        address     = col[6],
                    )

    return redirect("../sites")

@permission_required("sites.view_site")
def export_sites_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="sites.csv"'

    writer = csv.writer(response)
    writer.writerow(['customer','name','country','state','city','postal','address'])

    sites = Site.objects.all().values_list('customer','name','country','state','city','postal','address')
    for site in sites:
        writer.writerow(site)

    return response

@permission_required("sites_read")
def sites_grid(request, *args, **kwargs):
    template_name = 'sites/site_grid.html'

    if request.POST:
        move = request.POST.get("pagination")
        if move is not None and move != "":
            active_page = int(request.POST.get("active_page"))

            if move == "&laquo;" or move == "«":
                active_page -= 1
            elif move == "&raquo;" or move == "»":
                active_page += 1
            else:
                active_page = int(move)
    else:
        active_page = 1 #dynamic

    queryset = Site.objects.all().order_by('id')[10*(active_page-1):10*active_page]      #range of 10 items
    max_page = int(Site.objects.all().count()/10)+1                                         #total amount of pages = items/10 +1
    display_pages = [1,2,3,4,5]                                                             #max 5 pages at once
    if active_page >= 4:                                                                    #once 4 is passed
        display_pages = [x+(active_page-3) for x in display_pages]                          #move page count to follow active_page value

    context = {
        "object_list":queryset,
        "active_page":active_page,
        "max_page":max_page,
        "display":display_pages,
        "count":Site.objects.all().count()
    }

    return render(request, template_name, context=context)

class SiteDetailView(DetailView):
    template_name = 'sites/site_detail.html'

    def get_object(self):
    	id_ = self.kwargs.get("id")
    	return get_object_or_404(Site, id=id_)

class SiteCreateView(CreateView):
    template_name = 'sites/site_create.html'
    success_url = "../"

    form_class = SiteModelForm
    queryset = Site.objects.all()

    def get_success_url(self, **kwargs):
        return self.success_url

    def form_valid(self, form):
        return super().form_valid(form)

class SiteUpdateView(UpdateView):
    template_name = 'sites/site_update.html'
    form_class = SiteModelForm
    queryset = Site.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Site, id=id_)

    def form_valid(self, form):
        return super().form_valid(form)

class SiteDeleteView(DeleteView):
    template_name = 'sites/site_delete.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Site, id=id_)

    def get_success_url(self):
        return reverse("sites:site-grid")

sites/templates/sites/import_export_sites.html
<!-- Import/Export -->
<div class="col col-6">
  <div class="row">
    <div class="col">
      <form action="import-sites" method="POST" enctype="multipart/form-data"> {% csrf_token %}
        <input type="file" name="sites_file" value="Import sites CSV" />
        <input class="btn btn-success" type="submit" value="Import CSV" />
      </form>
    </div>
    <div class="col">
      <input class="btn btn-success" type="button" onclick="location.href='export-sites'" value="Export CSV sites" />
    </div>
  </div>
</div>

sites/templates/sites/site_create.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Création d'un nouveau site</h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Nouveau site</h2><br />
      </div>
      <div class="row justify-content-between">
        <label for="customer">Client :</label>&nbsp;
        <div style="color: red;">{{ form.customer.errors }}</div>
        {{ form.customer }}
      </div>
      <div class="row justify-content-between">
        <label for="name">Libellé :</label>&nbsp;
        <div style="color: red;">{{ form.name.errors }}</div>
        <input name="name" id="id_name" type="text" placeholder="Site CIC de Caen" />
      </div>
      <div class="row justify-content-between">
        <label for="country">Pays :</label>&nbsp;
        <div style="color: red;">{{ form.country.errors }}</div>
        <input name="country" id="id_country" type="text" placeholder="France" />
      </div>
      <div class="row justify-content-between">
        <label for="state">État :</label>&nbsp;
        <div style="color: red;">{{ form.state.errors }}</div>
        <input name="state" id="id_state" type="text" placeholder="Texas" />
      </div>
      <div class="row justify-content-between">
        <label for="city">Ville :</label>&nbsp;
        <div style="color: red;">{{ form.text.errors }}</div>
        <input name="city" id="id_city" type="text" placeholder="Paris" />
      </div>
      <div class="row justify-content-between">
        <label for="postal">Postal :</label>&nbsp;
        <div style="color: red;">{{ form.postal.errors }}</div>
        <input name="postal" id="id_postal" type="text" placeholder="75000" />
      </div>
      <div class="row justify-content-between">
        <label for="address">Adresse :</label>&nbsp;
        <div style="color: red;">{{ form.address.errors }}</div>
        <input name="address" id="id_address" type="text" placeholder="Rue de la Paix" />
      </div>
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-success" type="submit" value="Ajouter" />
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/sites'" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}

sites/templates/sites/site_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Suppression du site <b>{{ object.name }}</b></h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Voulez-vous supprimer le site <b>{{ object.label }}</b>?</h2><br />
      </div>
      <div class="row justify-content-around">
        <input class="col-4 btn btn-success" type="submit" value="Supprimer" />
        <input class="col-4 btn btn-danger" type="button" value="Annuler" onclick="location.href='/sites'" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}

sites/templates/sites/site_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Informations du site <b>{{ object.name }}</b></h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Site - <b>{{ object.name }}</b></h2>
      </div>
      <div class="row justify-content-between">
        <label for="customer">Client :</label>&nbsp;<input type="text" value="{{ object.customer.name }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="name">Libellé :</label>&nbsp;<input type="text" value="{{ object.name }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="country">Pays :</label>&nbsp;<input type="text" value="{{ object.country }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="state">État :</label>&nbsp;<input type="text" value="{{ object.state }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="city">Ville :</label>&nbsp;<input type="text" value="{{ object.city }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="postal">Postal :</label>&nbsp;<input type="text" value="{{ object.postal }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="address">Adresse :</label>&nbsp;<input type="text" value="{{ object.address }}" readonly="readonly" />
      </div>
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/sites'" />
      </div>
    </form>
  </div>
</div>

<hr />

{% include 'remove.html' %}

{% endblock content %}

sites/templates/sites/site_grid.html
{% extends 'base.html' %}

{% block content %}
<!-- Grid -->
<div class="table-responsive table-responsive-xl">

  {% include 'sites/sites_pagination.html' %}

  <table class="table table-striped table-hover">
    <thead class="thead-dark sticky-top">
      <tr>
          <th scope="col"><input type="checkbox" id="mass_select" onclick="massSelect()" /></th>
          <th scope="col">#</th>
          <th scope="col">Client</th>
          <th scope="col">Libellé</th>
          <th scope="col">Pays</th>
          <th scope="col">État</th>
          <th scope="col">Ville</th>
          <th scope="col">Postal</th>
          <th scope="col">Adresse</th>
      </tr>
    </thead>
    <tbody>
      {% for instance in object_list %}
      <tr>
          <td><input type="checkbox" name="select" id="{{ instance.id }}"/></td>
          <th scope="row" onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.id }}</th>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.customer.label }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.name }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.country }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.state }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.city }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.postal }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.address }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include 'actions.phtml' %}

{% endblock content %}

sites/templates/sites/site_update.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Mise à jour du site <b>{{ object.name }}</b></h1>
</div>

<hr />

{{ form.non_field_errors }}
<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Site - <b>{{ object.name }}</b></h2>
      </div>
      <div class="row justify-content-between">
        <label for="customer">Client :</label>&nbsp;
        <div style="color: red;">{{ form.customer.errors }}</div>
        {{ form.customer }}
      </div>
      <div class="row justify-content-between">
        <label for="name">Libellé :</label>&nbsp;
        <div style="color: red;">{{ form.name.errors }}</div>
        {{ form.name }}
      </div>
      <div class="row justify-content-between">
        <label for="country">Pays :</label>&nbsp;
        <div style="color: red;">{{ form.country.errors }}</div>
        {{ form.country }}
      </div>
      <div class="row justify-content-between">
        <label for="state">État :</label>&nbsp;
        <div style="color: red;">{{ form.state.errors }}</div>
        {{ form.state }}
      </div>
      <div class="row justify-content-between">
        <label for="city">Ville :</label>&nbsp;
        <div style="color: red;">{{ form.text.errors }}</div>
        {{ form.city }}
      </div>
      <div class="row justify-content-between">
        <label for="postal">Postal :</label>&nbsp;
        <div style="color: red;">{{ form.postal.errors }}</div>
        {{ form.postal }}
      </div>
      <div class="row justify-content-between">
        <label for="address">Adresse :</label>&nbsp;
        <div style="color: red;">{{ form.address.errors }}</div>
        {{ form.address }}
      </div>
      <br />
      <div class="row justify-content-around">
        <input class="col-4 btn btn-success" type="submit" value="Modifier" />
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/sites'" />
      </div>
    </form>
  </div>
</div>

<hr />

{% include 'remove.html' %}

{% endblock content %}

sites/templates/sites/sites_actions.html
<!-- Mass actions -->
<div class="col col-lg-2 input-group pt-2 pb-4">
  <div class="input-group-prepend">
    <button class="btn btn-outline-danger" type="button" onclick="massActions()">Actions</button>
  </div>
  <select class="custom-select" id="mass_action">
    <option selected>Choose...</option>
    <option value="1">Delete</option>
  </select>
</div>

sites/templates/sites/sites_pagination.html
<!-- Pagination -->
{% load i18n %}
{% trans request.path|slugify as path %}
<div class="sticky-top">
  {% include 'add.html' %}
  <div class="row">
    <div class="col">
      {% include 'pagination.html' %}
    </div>

    <div class="col col-6">
      {% include 'import_export.html' %}
    </div>

    {% include 'sites/sites_actions.html' %}
  </div>
</div>