customers/urls.py
from django.urls import path

from .views import (
    CustomerDetailView,
    CustomerCreateView,
    CustomerUpdateView,
    CustomerDeleteView,
    export_customers_csv,
    import_customers_csv,
    customers_grid
)

app_name = "customers"
urlpatterns = [
    path('', customers_grid, name='customer-index'),
    path('<int:id>/', CustomerDetailView.as_view(), name='customer-detail'),
    path('create/', CustomerCreateView.as_view(), name='customer-creation'),
    path('<int:id>/update/', CustomerUpdateView.as_view(), name='customer-update'),
    path('<int:id>/delete/', CustomerDeleteView.as_view(), name='customer-delete'),
    path('export', export_customers_csv, name='customer-export-csv'),
    path('import', import_customers_csv, name='customer-import-csv'),
]

www/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pminstrumentation.urls')),
    path('about', include('pminstrumentation.urls')),
    path('contact', include('pminstrumentation.urls')),
    path('legals', include('pminstrumentation.urls')),
    path('customers/', include('customers.urls')),
    path('sites/', include('sites.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('planning/', include('planning.urls')),
    path('notifications/', include('notifications.urls')),
    path('tickets/', include('tickets.urls')),
]

customers/models.py
from django.db import models
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.validators import MaxValueValidator, MinValueValidator

class Customer(models.Model):
    name = models.CharField(max_length=500)
    label = models.CharField(max_length=500)
    siren = models.IntegerField(validators=[MinValueValidator(100000000),MaxValueValidator(999999999)]) #9 digits

    def get_absolute_url(self):
        return reverse("customers:customer-detail", kwargs={"id":self.id})

customers/forms.py
from django import forms

from .models import Customer

class CustomerModelForm(forms.ModelForm):
    class Meta:
            model = Customer
            fields = [
                "name",
                "label",
                "siren"
            ]

customers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required

from .models import Customer
from .forms import CustomerModelForm

import csv, os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

@login_required
@permission_required("customers_write","customers_all")
def import_customers_csv(request):
    if request.method == 'POST' and request.FILES:                              #avoid GET and empty file sending
        file = request.FILES['file'].read().decode("utf-8")             #get the file and open it to read with UTF-8 compatibility
        rows = file.split("\n")                                                 #get rows (separator : \n)
        for row in rows:                                                        #loop through rows
            if row != '':                                                       #avoid last empty row
                col = row.split(",")                                            #get columns (delimiter : ,)
                if col[0] != 'name':                                            #skip header
                    _, created = Customer.objects.get_or_create(                #check existence in database to avoid duplicate
                        name        = col[0],
                        label       = col[1],
                        siren       = col[2],
                    )

    return redirect("../customers")

@login_required
@permission_required("customers_read","customers_all")
def export_customers_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="customers.csv"'

    writer = csv.writer(response)
    writer.writerow(['name','label','siren'])

    customers = Customer.objects.all().values_list('name','label','siren')
    for customer in customers:
        writer.writerow(customer)

    return response

@login_required
@permission_required("customers_read","customers_all")
def customers_grid(request, *args, **kwargs):
    template_name = 'customers/customer_grid.html'

    if request.POST:
        move = request.POST.get("pagination")
        if move is not None and move != "":
            active_page = int(request.POST.get("active_page"))

            if move == "&laquo;" or move == "«":
                active_page -= 1
            elif move == "&raquo;" or move == "»":
                active_page += 1
            else:
                active_page = int(move)
    else:
        active_page = 1 #dynamic

    queryset = Customer.objects.all().order_by('id')[10*(active_page-1):10*active_page]      #range of 10 items
    max_page = int(Customer.objects.all().count()/10)+1                                         #total amount of pages = items/10 +1
    display_pages = [1,2,3,4,5]                                                             #max 5 pages at once
    if active_page >= 4:                                                                    #once 4 is passed
        display_pages = [x+(active_page-3) for x in display_pages]                          #move page count to follow active_page value

    context = {
        "object_list":queryset,
        "active_page":active_page,
        "max_page":max_page,
        "display":display_pages,
        "count":Customer.objects.all().count()
    }

    return render(request, template_name, context=context)

class CustomerDetailView(DetailView):
    template_name = 'customers/customer_detail.html'

    def get_object(self):
    	id_ = self.kwargs.get("id")
    	return get_object_or_404(Customer, id=id_)

class CustomerCreateView(CreateView):
    template_name = 'customers/customer_create.html'
    success_url = "../"

    form_class = CustomerModelForm
    queryset = Customer.objects.all()

    def get_success_url(self, **kwargs):
        return self.success_url

    def form_valid(self, form):
        return super().form_valid(form)

class CustomerUpdateView(UpdateView):
    template_name = 'customers/customer_update.html'
    form_class = CustomerModelForm
    queryset = Customer.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Customer, id=id_)

    def form_valid(self, form):
        return super().form_valid(form)

class CustomerDeleteView(DeleteView):
    template_name = 'customers/customer_delete.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Customer, id=id_)

    def get_success_url(self):
        return reverse("customers:customer-index")

customers/templates/customers/customer_create.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Création d'un nouveau client</h1>
</div>

<hr />

{{ form.non_field_errors }}
<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Nouveau client</h2><br />
      </div>
      <div class="row justify-content-between">
        <label for="label">Libellé :</label>&nbsp;
        <div style="color: red;">{{ form.label.errors }}</div>
        <input name="label" id="id_label" type="text" placeholder="CIC" />
      </div>
      <div class="row justify-content-between">
        <label for="name">Dénomination :</label>&nbsp;
        <div style="color: red;">{{ form.name.errors }}</div>
        <input name="name" id="id_name" type="text" placeholder="Crédit Industriel et Commercial" />
      </div>
      <div class="row justify-content-between">
        <label for="siren">SIREN :</label>&nbsp;
        <div style="color: red;">{{ form.siren.errors }}</div>
        <input name="siren" id="id_siren" type="text" placeholder="315066811" />
      </div>
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-success" type="submit" value="Ajouter" />
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/customers'" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}

customers/templates/customers/customer_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Suppression du client <b>{{ object.name }}</b></h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Voulez-vous supprimer le client <b>{{ object.label }}</b>?</h2><br />
      </div>
      <div class="row justify-content-around">
        <input class="col-4 btn btn-success" type="submit" value="Supprimer" />
        <input class="col-4 btn btn-danger" type="button" value="Annuler" onclick="location.href='/customers'" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}

customers/templates/customers/customer_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Informations du client <b>{{ object.label }}</b></h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Client - <b>{{ object.label }}</b></h2>
      </div>
      <div class="row justify-content-between">
        <label for="label">Libellé :</label>&nbsp;<input type="text" value="{{ object.label }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="name">Dénomination :</label>&nbsp;<input type="text" value="{{ object.name }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="siren">SIREN :</label>&nbsp;<input type="text" value="{{ object.siren }}" readonly="readonly" />
      </div>
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/customers'" />
      </div>
    </form>
  </div>
</div>

<hr />

{% include 'remove.html' %}

{% endblock content %}

customers/templates/customers/customer_grid.html
{% extends 'base.html' %}

{% block content %}
<!-- Grid -->
<div class="table-responsive table-responsive-xl">

  {% include 'customers/customers_pagination.html' %}

  <table class="table table-striped table-hover">
    <thead class="thead-dark sticky-top">
      <tr>
          <th scope="col"><input type="checkbox" id="mass_select" onclick="massSelect()" /></th>
          <th scope="col">#</th>
          <th scope="col">Nom</th>
          <th scope="col">Libellé</th>
          <th scope="col">Siren</th>
      </tr>
    </thead>
    <tbody>
      {% for instance in object_list %}
      <tr>
          <td><input type="checkbox" name="select" id="{{ instance.id }}"/></td>
          <th scope="row" onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.id }}</th>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.name }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.label }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.siren }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include 'actions.phtml' %}

{% endblock content %}

customers/templates/customers/customer_update.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Mise à jour du client <b>{{ object.name }} - {{ object.label }} - {{ object.siren }}</b></h1>
</div>

<hr />

{{ form.non_field_errors }}
<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Client - <b>{{ object.label }}</b></h2>
      </div>
      <div class="row justify-content-between">
        <label for="label">Libellé :</label>&nbsp;
        <div style="color: red;">{{ form.label.errors }}</div>
        {{ form.label }}
      </div>
      <div class="row justify-content-between">
        <label for="name">Dénomination :</label>&nbsp;
        <div style="color: red;">{{ form.name.errors }}</div>
        {{ form.name }}
      </div>
      <div class="row justify-content-between">
        <label for="siren">SIREN :</label>&nbsp;
        <div style="color: red;">{{ form.siren.errors }}</div>
        {{ form.siren }}
      </div>
      <br />
      <div class="row justify-content-around">
        <input class="col-4 btn btn-success" type="submit" value="Modifier" />
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/customers'" />
      </div>
    </form>
  </div>
</div>

<hr />

{% include 'remove.html' %}

{% endblock content %}

customers/templates/customers/customers_actions.html
<!-- Mass actions -->
<div class="col col-lg-2 input-group pt-2 pb-4">
  <div class="input-group-prepend">
    <button class="btn btn-outline-danger" type="button" onclick="massActions()">Actions</button>
  </div>
  <select class="custom-select" id="mass_action">
    <option selected>Choose...</option>
    <option value="1">Delete</option>
  </select>
</div>

customers/templates/customers/customers_pagination.html
<!-- Pagination -->
{% load i18n %}
{% trans request.path|slugify as path %}
<div class="sticky-top">
  {% include 'add.html' %}
  <div class="row">
    <div class="col">
      {% include 'pagination.html' %}
    </div>

    <div class="col col-6">
      {% include 'import_export.html' %}
    </div>

    {% include 'customers/customers_actions.html' %}
  </div>
</div>