products/urls.py
from django.urls import path

from .views import (
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    export_products_csv,
    import_products_csv,
    products_grid
)

app_name = "products"
urlpatterns = [
    path('', products_grid, name='product-grid'),
    path('<int:id>/', ProductDetailView.as_view(), name='product-detail'),
    path('create/', ProductCreateView.as_view(), name='product-creation'),
    path('<int:id>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('<int:id>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    path('export', export_products_csv, name='product-export-csv'),
    path('import', import_products_csv, name='product-import-csv'),
]

www/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pminstrumentation.urls')),
    path('about', include('pminstrumentation.urls')),
    path('contact', include('pminstrumentation.urls')),
    path('legals', include('pminstrumentation.urls')),
    path('customers/', include('customers.urls')),
    path('sites/', include('sites.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('planning/', include('planning.urls')),
    path('notifications/', include('notifications.urls')),
    path('tickets/', include('tickets.urls')),
]

products/models.py
from django.db import models
from django.urls import reverse
from django.http import HttpResponseRedirect

from categories.models import Category

class Product(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    reference = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse("products:product-detail", kwargs={"id":self.id})

products/forms.py
from django import forms

from .models import Product

class ProductModelForm(forms.ModelForm):
    class Meta:
            model = Product
            fields = [
                "category",
                "name",
                "description",
                "reference",
            ]

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required

from categories.models import Category
from .models import Product
from .forms import ProductModelForm

import csv, os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

@login_required
@permission_required("products_write","products_all")
def import_products_csv(request):
    if request.method == 'POST' and request.FILES:
        file = request.FILES['file'].read().decode("utf-8")
        rows = file.split("\n")
        for row in rows:
            if row != '':
                col = row.split(",")
                if col[0] != 'category':    #skip header
                    _, cat = Category.objects.get_or_create(
                        id=col[0],
                        defaults={"name":"Default category name"}
                    )

                    if isinstance(cat, Category):
                        category = cat
                    else:
                        category = _

                    _, created = Product.objects.get_or_create(
                        category    = category,
                        name        = col[1],
                        description = col[2],
                        reference   = col[3]
                    )

    return redirect(".")

@login_required
def export_products_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="products.csv"'

    writer = csv.writer(response)
    writer.writerow(['category','name', 'description', 'reference'])

    products = Product.objects.all().values_list('category','name', 'description', 'reference')
    for product in products:
        writer.writerow(product)

    return response

@login_required
def products_grid(request, *args, **kwargs):
    template_name = 'products/product_grid.html'

    if request.POST:
        move = request.POST.get("pagination")
        if move is not None and move != "":
            active_page = int(request.POST.get("active_page"))

            if move == "&laquo;" or move == "«":
                active_page -= 1
            elif move == "&raquo;" or move == "»":
                active_page += 1
            else:
                active_page = int(move)
    else:
        active_page = 1 #dynamic

    queryset = Product.objects.all().order_by('id')[10*(active_page-1):10*active_page]      #range of 10 items
    max_page = int(Product.objects.all().count()/10)+1                                         #total amount of pages = items/10 +1
    display_pages = [1,2,3,4,5]                                                             #max 5 pages at once
    if active_page >= 4:                                                                    #once 4 is passed
        display_pages = [x+(active_page-3) for x in display_pages]                          #move page count to follow active_page value

    context = {
        "object_list":queryset,
        "active_page":active_page,
        "max_page":max_page,
        "display":display_pages,
        "count":Product.objects.all().count()
    }

    return render(request, template_name, context=context)

class ProductDetailView(DetailView):
    template_name = 'products/product_detail.html'

    @login_required
    def get_object(self):
    	id_ = self.kwargs.get("id")
    	return get_object_or_404(Product, id=id_)

class ProductCreateView(CreateView):
    template_name = 'products/product_create.html'
    success_url = "../"

    form_class = ProductModelForm
    queryset = Product.objects.all()
    @login_required
    def get_success_url(self, form):
        return success_url
    @login_required
    def form_valid(self, form):
        return super().form_valid(form)

class ProductUpdateView(UpdateView):
    template_name = 'products/product_update.html'
    form_class = ProductModelForm
    queryset = Product.objects.all()
    @login_required
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Product, id=id_)
    @login_required
    def form_valid(self, form):
        return super().form_valid(form)

class ProductDeleteView(DeleteView):
    template_name = 'products/product_delete.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Product, id=id_)

    def get_success_url(self):
        return reverse("products:product-grid")

products/templates/products/import_export_products.html
<!-- Import/Export -->
<div class="col col-6">
  <div class="row">
    <div class="col">
      <form action="/products/import-products" method="POST" enctype="multipart/form-data"> {% csrf_token %}
        <div class="form-group">
        <input type="file" name="products_file" value="Import produits CSV" />
        <input class="btn btn-success" type="submit" value="Import CSV" />
      </div>
      </form>
    </div>
    <div class="col">
      <input class="btn btn-success" type="button" onclick="location.href='/products/export-products'" value="Export CSV produits" />
    </div>
  </div>
</div>

products/templates/products/product_create.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Création d'un nouveau produit</h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Nouveau produit</h2><br />
      </div>
      <div class="row justify-content-between">
        <label for="category">Catégorie :</label>&nbsp;
        <div style="color: red;">{{ form.category.errors }}</div>
        {{ form.category }}
      </div>
      <div class="row justify-content-between">
        <label for="name">Nom :</label>&nbsp;
        <div style="color: red;">{{ form.name.errors }}</div>
        <input name="name" id="id_name" type="text" placeholder="Capteur de force 2 Axes | 16 kN à 63 kN Fz" />
      </div>
      <div class="row justify-content-between">
        <label for="description">Description :</label>&nbsp;
        <div style="color: red;">{{ form.description.errors }}</div>
        <textarea name="description" id="id_description" name="description" rows="5" cols="40" placeholder=" Capteur de force Fz - Mz
    EM : 16kN/63kN et 220 Nm à 900 Nm
    Non-linéarité : ± 0.05%
    Signal de sortie: 2 mV/V
    Hytereresis: ± 0.05%
    Construction: Acier
    Sensibilité à la température : < 0.0015% / °Cnecter"></textarea>
      </div>
      <div class="row justify-content-between">
        <label for="reference">Référence :</label>&nbsp;
        <div style="color: red;">{{ form.reference.errors }}</div>
        <input name="reference" id="id_reference" type="text" placeholder="DA2816" />
      </div>
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-success" type="submit" value="Ajouter" />
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/products'" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}

products/templates/products/product_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Suppression du produit <b>{{ object.name }}</b></h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Voulez-vous supprimer le produit <b>{{ object.name }}</b>?</h2><br />
      </div>
      <div class="row justify-content-around">
        <input class="col-4 btn btn-success" type="submit" value="Supprimer" />
        <input class="col-4 btn btn-danger" type="button" value="Annuler" onclick="location.href='/products'" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Informations du produit <b>{{ object.name }}</b></h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Produit - <b>{{ object.name }}</b></h2>
      </div>
      <div class="row justify-content-between">
        <label for="category">Catégorie :</label>&nbsp;<input type="text" value="{{ object.category.name }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="name">Nom :</label>&nbsp;<input type="text" value="{{ object.name }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="description">Description :</label>&nbsp;
        <textarea class="bg-light" name="description" rows="5" cols="50" readonly="readonly" >{{ object.description }}</textarea>
      </div>
      <div class="row justify-content-between">
        <label for="reference">Référence :</label>&nbsp;<input type="text" value="{{ object.reference }}" readonly="readonly" />
      </div>
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/products'" />
      </div>
    </form>
  </div>
</div>

<hr />

{% include 'remove.html' %}

{% endblock content %}

products/templates/products/product_grid.html
{% extends 'base.html' %}

{% block content %}
<!-- Grid -->
<div class="table-responsive table-responsive-xl">

  {% include 'products/products_pagination.html' %}

  <table class="table table-striped table-hover">
    <thead class="thead-dark sticky-top">
      <tr>
          <th scope="col">#</th>
          <th scope="col">Catégorie</th>
          <th scope="col">Nom</th>
          <th scope="col">Description</th>
          <th scope="col">Référence</th>
      </tr>
    </thead>
    <tbody>
      {% for instance in object_list %}
      <tr>
          <th scope="row" onclick="window.open('http://pminstrumentation.com/{{ instance.reference|slugify }}-{{ instance.name|slugify }}')" style="color:#007bff; cursor: pointer;">{{ instance.id }}</th>
          <td onclick="window.open('http://pminstrumentation.com/{{ instance.reference|slugify }}-{{ instance.name|slugify }}')" style="color:#007bff; cursor: pointer;">{{ instance.category.name }}</td>
          <td onclick="window.open('http://pminstrumentation.com/{{ instance.reference|slugify }}-{{ instance.name|slugify }}')" style="color:#007bff; cursor: pointer;">{{ instance.name }}</td>
          <td onclick="window.open('http://pminstrumentation.com/{{ instance.reference|slugify }}-{{ instance.name|slugify }}')" style="color:#007bff; cursor: pointer;">{{ instance.description }}</td>
          <td onclick="window.open('http://pminstrumentation.com/{{ instance.reference|slugify }}-{{ instance.name|slugify }}')" style="color:#007bff; cursor: pointer;">{{ instance.reference }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}

{% include 'products/import_export_products.html' %}

{% for instance in object_list %}
  <p>{{ instance.id }} - <a href="{{ instance.get_absolute_url }}">{{ instance.name }}</a></p>
{% endfor %}

{% endblock content %}

products/templates/products/product_update.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Mise à jour du produit <b>{{ object.name }}</b></h1>
</div>

<hr />

{{ form.non_field_errors }}
<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Produit - <b>{{ object.name }}</b></h2>
      </div>
      <div class="row justify-content-between">
        <label for="category">Catégorie :</label>&nbsp;
        <div style="color: red;">{{ form.category.errors }}</div>
        {{ form.category }}
      </div>
      <div class="row justify-content-between">
        <label for="name">Nom :</label>&nbsp;
        <div style="color: red;">{{ form.name.errors }}</div>
        {{ form.name }}
      </div>
      <div class="row justify-content-between">
        <label for="country">Description :</label>&nbsp;
        <div style="color: red;">{{ form.description.errors }}</div>
        {{ form.description }}
      </div>
      <div class="row justify-content-between">
        <label for="reference">Référence :</label>&nbsp;
        <div style="color: red;">{{ form.reference.errors }}</div>
        {{ form.reference }}
      </div>
      <br />
      <div class="row justify-content-around">
        <input class="col-4 btn btn-success" type="submit" value="Modifier" />
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/products'" />
      </div>
    </form>
  </div>
</div>

<hr />

{% include 'remove.html' %}

{% endblock content %}

products/templates/products/products_actions.html
<!-- Mass actions -->
<div class="col col-lg-2 input-group pt-2 pb-4">
  <div class="input-group-prepend">
    <button class="btn btn-outline-danger" type="button" onclick="massActions()">Actions</button>
  </div>
  <select class="custom-select" id="mass_action">
    <option selected>Choose...</option>
    <option value="1">Delete</option>
  </select>
</div>

products/templates/products/products_pagination.html
<!-- Pagination -->
{% load i18n %}
{% trans request.path|slugify as path %}
<div class="sticky-top">
  {% include 'add.html' %}
  <div class="row">
    <div class="col">
      {% include 'pagination.html' %}
    </div>

    <div class="col col-6">
      {% include 'import_export.html' %}
    </div>

    {% include 'products/products_actions.html' %}
  </div>
</div>