notifications/urls.py
from django.urls import path

from .views import (
    NotificationDetailView,
    NotificationCreateView,
    NotificationUpdateView,
    NotificationDeleteView,
    export_notifications_csv,
    import_notifications_csv,
    notifications_grid
)

app_name = "notifications"
urlpatterns = [
    path('', notifications_grid, name='notification-grid'),
    path('<int:id>/', NotificationDetailView.as_view(), name='notification-detail'),
    path('create/', NotificationCreateView.as_view(), name='notification-creation'),
    path('<int:id>/update/', NotificationUpdateView.as_view(), name='notification-update'),
    path('<int:id>/delete/', NotificationDeleteView.as_view(), name='notification-delete'),
    path('export', export_notifications_csv, name='notification-export-csv'),
    path('import', import_notifications_csv, name='notification-import-csv'),
]

www/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pminstrumentation.urls')),
    path('about', include('pminstrumentation.urls')),
    path('contact', include('pminstrumentation.urls')),
    path('legals', include('pminstrumentation.urls')),
    path('customers/', include('customers.urls')),
    path('sites/', include('sites.urls')),
    path('categories/', include('categories.urls')),
    path('products/', include('products.urls')),
    path('planning/', include('planning.urls')),
    path('notifications/', include('notifications.urls')),
    path('tickets/', include('tickets.urls')),
]

notifications/models.py
from django.db import models
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils.timezone import datetime

from customers.models import Customer
from products.models import Product

class Type(models.Model):
    type = models.CharField(max_length=50)

class State(models.Model):
    state = models.CharField(max_length=20)

class Notification(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.today())
    automatized = models.BooleanField(default=False)
    recurrence = models.CharField(max_length=10, null=True,blank=True)
    message = models.TextField(default="")

    def get_absolute_url(self):
        return reverse("notifications:notification-detail", kwargs={"id":self.id})

notifications/forms.py
from django import forms

from .models import Notification

class NotificationModelForm(forms.ModelForm):
    class Meta:
            model = Notification
            fields = [
                "customer",
                "product",
                "state",
                "type",
                "date",
                "automatized",
                "recurrence",
            ]

notifications/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from categories.models import Category
from customers.models import Customer
from products.models import Product
from .models import Notification, Type, State
from .forms import NotificationModelForm

import csv, os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def import_notifications_csv(request):
    if request.method == 'POST' and request.FILES:
        file = request.FILES['file'].read().decode("utf-8")
        rows = file.split("\n")
        for row in rows:
            if row != '':
                col = row.split(",")
                if col[0] != 'date':    #skip header
                    if(col[2] != ""):
                        _cus, cus = Customer.objects.get_or_create(
                            id=col[2],
                            defaults={
                            "name":"Default customer name",
                            "siren":"123456789"}
                        )
                    _cat, cat = Category.objects.get_or_create(
                        id=1,
                        defaults={
                        "name":"Default category name"}
                    )

                    if isinstance(cat, Category):
                        category = cat
                    else:
                        category = _cat

                    _pro, pro = Product.objects.get_or_create(
                        id=col[3],
                        defaults={
                        "name":"Default product name",
                        "category":category}
                    )
                    _typ, typ = Type.objects.get_or_create(
                        id=col[1],
                        defaults={"type":"Default type"}
                    )
                    _sta, sta = State.objects.get_or_create(
                        id=col[4],
                        defaults={"state":"Default state"}
                    )

                    if(col[2] != ""):
                        if isinstance(cus, Customer):
                            customer = cus
                        else:
                            customer = _cus
                    else:
                        customer = None

                    if isinstance(pro, Product):
                        product = pro
                    else:
                        product = _pro

                    if isinstance(typ, Type):
                        type = typ
                    else:
                        type = _typ

                    if isinstance(sta, State):
                        state = sta
                    else:
                        state = _sta

                    _, created = Notification.objects.get_or_create(
                        customer    = customer,
                        product     = product,
                        state       = state,
                        type        = type,
                        date        = col[0]
                    )

    return redirect(".")

def export_notifications_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="notifications.csv"'

    writer = csv.writer(response)
    writer.writerow(['date','type', 'customer', 'product', 'state'])

    notifications = Notification.objects.all().values_list('date','type', 'customer', 'product', 'state')
    for notification in notifications:
        writer.writerow(notification)

    return response

def notifications_grid(request, *args, **kwargs):
    template_name = 'notifications/notification_grid.html'
    if request.POST:
        move = request.POST.get("pagination")
        if move is not None and move != "":
            active_page = int(request.POST.get("active_page"))

            if move == "&laquo;" or move == "«":
                active_page -= 1
            elif move == "&raquo;" or move == "»":
                active_page += 1
            else:
                active_page = int(move)
    else:
        active_page = 1 #dynamic

    queryset = Notification.objects.all().order_by('id')[10*(active_page-1):10*active_page]      #range of 10 items
    max_page = int(Notification.objects.all().count()/10)+1                                         #total amount of pages = items/10 +1
    display_pages = [1,2,3,4,5]                                                             #max 5 pages at once
    if active_page >= 4:                                                                    #once 4 is passed
        display_pages = [x+(active_page-3) for x in display_pages]                          #move page count to follow active_page value

    context = {
        "object_list":queryset,
        "active_page":active_page,
        "max_page":max_page,
        "display":display_pages,
        "count":Notification.objects.all().count()
    }

    return render(request, template_name, context=context)

class NotificationDetailView(DetailView):
    template_name = 'notifications/notification_detail.html'

    def get_object(self):
    	id_ = self.kwargs.get("id")
    	return get_object_or_404(Notification, id=id_)

class NotificationCreateView(CreateView):
    template_name = 'notifications/notification_create.html'
    success_url = "../"

    form_class = NotificationModelForm
    queryset = Notification.objects.all()

    def get_success_url(self, **kwargs):
        return self.success_url

    def form_valid(self, form):
        return super().form_valid(form)

class NotificationUpdateView(UpdateView):
    template_name = 'notifications/notification_update.html'
    form_class = NotificationModelForm
    queryset = Notification.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Notification, id=id_)

    def form_valid(self, form):
        return super().form_valid(form)

class NotificationDeleteView(DeleteView):
    template_name = 'notifications/notification_delete.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Notification, id=id_)

    def get_success_url(self):
        return reverse("notifications:notification-grid")

notifications/templates/notifications/notification_create.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Création d'une nouvelle notification</h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Nouvelle notification</h2><br />
      </div>
      <div class="row justify-content-between">
        <label for="customer">Client :</label>&nbsp;
        <div style="color: red;">{{ form.customer.errors }}</div>
        {{ form.customer }}
      </div>
      <div class="row justify-content-between">
        <label for="product">Produit :</label>&nbsp;
        <div style="color: red;">{{ form.product.errors }}</div>
        {{ form.product }}
      </div>
      <div class="row justify-content-between">
        <label for="type">Type :</label>&nbsp;
        <div style="color: red;">{{ form.type.errors }}</div>
        {{ form.type }}
      </div>
      <div class="row justify-content-between">
        <label for="state">État :</label>&nbsp;
        <div style="color: red;">{{ form.state.errors }}</div>
        {{ form.state }}
      </div>
      <div class="row justify-content-between">
        <label for="date">Date :</label>&nbsp;
        <div style="color: red;">{{ form.date.errors }}</div>
        <input name="date" id="id_date" name="date" id="id_date" type="datetime" placeholder="{% now "Y-m-d H:i:s" %}" />
      </div>
      <div class="row justify-content-between">
        <label for="automatized">Automatisée :</label>&nbsp;
        <div style="color: red;">{{ form.automatized.errors }}</div>
        {{ form.automatized }}
      </div>
      <div class="row justify-content-between">
        <label for="recurrence">Récurrence :</label>&nbsp;
        <div style="color: red;">{{ form.recurrence.errors }}</div>
        <input name="recurrence" id="id_recurrence" type="text" placeholder="1D2M0Y" />
      </div>
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-success" type="submit" value="Ajouter" />
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/notifications'" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}

notifications/templates/notifications/notification_delete.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Suppression d'une notification <b>{{ object.customer.label }} - {{ object.product.name}} - {{object.type.type }}</b></h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Voulez-vous supprimer la notification <b>{{ object.state.state }} - {{ object.date }} {% if object.automatized %} - {{ object.recurrence }}{% endif %}</b>?</h2><br />
      </div>
      <div class="row justify-content-around">
        <input class="col-4 btn btn-success" type="submit" value="Supprimer" />
        <input class="col-4 btn btn-danger" type="button" value="Annuler" onclick="location.href='/notifications'" />
      </div>
    </form>
  </div>
</div>

{% endblock content %}

notifications/templates/notifications/notification_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Informations de la notification <b>{{ object.customer.label }} - {{ object.product.name}} - {{object.type.type }}</b></h1>
</div>

<hr />

<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Notification - <b>{{ object.state.state }} - {{ object.date }} {% if object.automatized %} - {{ object.recurrence }}{% endif %}</b></h2>
      </div>

      <div class="row justify-content-between">
        <label for="customer">Client :</label>&nbsp;<input type="text" value="{{ object.customer.label }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="product">Produit :</label>&nbsp;<input type="text" value="{{ object.product.name }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="type">Type :</label>&nbsp;<input type="text" value="{{ object.type.type }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="state">État :</label>&nbsp;<input type="text" value="{{ object.state.state }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="date">Date :</label>&nbsp;<input type="text" value="{{ object.date }}" readonly="readonly" />
      </div>
      <div class="row justify-content-between">
        <label for="automatized">Automatisée :</label>&nbsp;<input type="checkbox" name="automatized" value="automatized" {% if object.automatized is True %}checked="checked"{% endif %} readonly="readonly" />
      </div>
      {% if object.automatized is True %}
      <div class="row justify-content-between">
        <label for="recurrence">Récurrence :</label>&nbsp;<input type="text" value="{{ object.recurrence }}" readonly="readonly" />
      </div>
      {% endif %}
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/notifications'" readonly="readonly" />
      </div>
    </form>
  </div>
</div>

<hr />

{% include 'remove.html' %}

{% endblock content %}

notifications/templates/notifications/notification_grid.html
{% extends 'base.html' %}

{% block content %}
<!-- Grid -->
<div class="table-responsive table-responsive-xl">

  {% include 'notifications/notifications_pagination.html' %}

  <table class="table table-striped table-hover">
    <thead class="thead-dark sticky-top">
      <tr>
          <th scope="col"><input type="checkbox" id="mass_select" onclick="massSelect()" /></th>
          <th scope="col">#</th>
          <th scope="col">Date</th>
          <th scope="col">Type</th>
          <th scope="col">Client</th>
          <th scope="col">Produit</th>
          <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for instance in object_list %}
      <tr>
          <td><input type="checkbox" name="select" id="{{ instance.id }}"/></td>
          <th scope="row" onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.id }}</th>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.date|date:"D d M Y H:i:s" }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.type.type }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.customer.name }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.product.name }}</td>
          <td onclick="location.href='{{ instance.get_absolute_url }}'" style="color:#007bff; cursor: pointer;">{{ instance.state.state }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include 'actions.phtml' %}

{% endblock content %}

notifications/templates/notifications/notification_update.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-5 mb-5 d-flex justify-content-center align-items-center">
  <h1>Mise à jour de la notification <b>{{ object.customer.label }} - {{ object.product.name}} - {{object.type.type }}</b></h1>
</div>

<hr />

{{ form.non_field_errors }}
<div class="d-flex justify-content-center align-items-center">
  <div class="mt-5 p-5 bg-light border border-secondary rounded-right">
    <form class="mr-5 ml-5" action="." method="POST"> {% csrf_token %}
      <div class="row justify-content-center mb-3">
        <h2>Notification - <b>{{ object.state.state }} - {{ object.date }} {% if object.automatized %} - {{ object.recurrence }}{% endif %}</b></h2>
      </div>

      <div class="row justify-content-between">
        <label for="customer">Client :</label>&nbsp;
        <div style="color: red;">{{ form.customer.errors }}</div>
        {{ form.customer }}
      </div>
      <div class="row justify-content-between">
        <label for="product">Produit :</label>&nbsp;
        <div style="color: red;">{{ form.product.errors }}</div>
        {{ form.product }}
      </div>
      <div class="row justify-content-between">
        <label for="type">Type :</label>&nbsp;
        <div style="color: red;">{{ form.type.errors }}</div>
        {{ form.type }}
      </div>
      <div class="row justify-content-between">
        <label for="state">État :</label>&nbsp;
        <div style="color: red;">{{ form.state.errors }}</div>
        {{ form.state }}
      </div>
      <div class="row justify-content-between">
        <label for="date">Date :</label>&nbsp;
        <div style="color: red;">{{ form.date.errors }}</div>
        {{ form.date }}
      </div>
      <div class="row justify-content-between">
        <label for="automatized">Automatisée :</label>&nbsp;
        <div style="color: red;">{{ form.automatized.errors }}</div>
        {{ form.automatized }}
      </div>
      {% if object.automatized is True %}
      <div class="row justify-content-between">
        <label for="recurrence">Récurrence :</label>&nbsp;
        <div style="color: red;">{{ form.recurrence.errors }}</div>
        {{ form.recurrence }}
      </div>
      {% endif %}
      <br />
      <div class="row justify-content-around mt-3">
        <input class="col-4 btn btn-success" type="submit" value="Modifier" />
        <input class="col-4 btn btn-danger" type="button" value="Retour" onclick="location.href='/notifications'" />
      </div>
    </form>
  </div>
</div>

<hr />

{% include 'remove.html' %}

{% endblock content %}

notifications/templates/notifications/notifications_actions.html
<!-- Mass actions -->
<div class="col col-lg-2 input-group pt-2 pb-4">
  <div class="input-group-prepend">
    <button class="btn btn-outline-danger" type="button" onclick="massActions()">Actions</button>
  </div>
  <select class="custom-select" id="mass_action">
    <option selected>Choose...</option>
    <option value="1">Delete</option>
  </select>
</div>

notifications/templates/notifications/notifications_pagination.html
<!-- Pagination -->
{% load i18n %}
{% trans request.path|slugify as path %}
<div class="sticky-top">
  {% include 'add.html' %}
  <div class="row">
    <div class="col">
      {% include 'pagination.html' %}
    </div>

    <div class="col col-6">
      {% include 'import_export.html' %}
    </div>

    {% include 'notifications/notifications_actions.html' %}
  </div>
</div>